medis/apps/stats/urls.py
from django.conf.urls import patterns, url

from medis.apps.stats.views import (MonthStatsView, SpecialityStatsView)

urlpatterns = patterns(
    '',
    url(r'^month/$', MonthStatsView.as_view(), name='month'),
    url(r'^spec/', SpecialityStatsView.as_view(), name='month-speciality'),
)

medis/urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',

    url(r'^stats/', include('medis.apps.stats.urls', namespace='stats')),

    url(r'^admin/', include(admin.site.urls)),
)

medis/apps/stats/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import admin
from django.core.exceptions import ObjectDoesNotExist
from django.db import models


class SpecialityManager(models.Manager):
    def get_or_none(self, *args, **kwargs):
        try:
            return self.get(*args, **kwargs)
        except ObjectDoesNotExist:
            return None


class Speciality(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование специальности')

    class Meta:
        verbose_name = 'Специальность'
        verbose_name_plural = 'Специальности'
        ordering = ['-pk']

    def __unicode__(self):
        return self.name

    objects = SpecialityManager()


admin.site.register(Speciality)


class Doctor(models.Model):
    name = models.CharField(max_length=255, verbose_name='ФИО врача')
    speciality = models.ForeignKey(Speciality)

    class Meta:
        verbose_name = 'Врач'
        verbose_name_plural = 'Врачи'
        ordering = ['name', '-pk']

    def __unicode__(self):
        return self.name

admin.site.register(Doctor)


class Patient(models.Model):
    name = models.CharField(max_length=255, verbose_name='ФИО пациента')

    class Meta:
        verbose_name = 'Пациент'
        verbose_name_plural = 'Пациенты'
        ordering = ['name', '-pk']

    def __unicode__(self):
        return self.name

admin.site.register(Patient)


class TicketManager(models.Manager):
    def get_monthly_stats(self, month, year):
        data = []
        for speciality in Speciality.objects.all():
            tickets = Ticket.objects.filter(doctor__in=speciality.doctor_set.all(), datetime__month=month,
                                            datetime__year=year)
            patients = tickets.exclude(patient__isnull=True)
            data.append({
                'pk': speciality.pk,
                'name': speciality.name,
                'tickets': tickets.count(),
                'patients': patients.count()
            })
        return data

    def get_speciality_stats(self, speciality, month, year):
        data = []
        for doctor in Doctor.objects.filter(speciality=speciality):
            tickets = Ticket.objects.filter(doctor=doctor, datetime__month=month, datetime__year=year)
            patients = tickets.exclude(patient__isnull=True)
            data.append({
                'pk': doctor.pk,
                'name': doctor.name,
                'tickets': tickets.count(),
                'patients': patients.count()
            })
        return data


class Ticket(models.Model):
    doctor = models.ForeignKey(Doctor)
    datetime = models.DateTimeField()
    patient = models.ForeignKey(Patient, null=True, blank=True)

    class Meta:
        verbose_name = 'Талон'
        verbose_name_plural = 'Талоны'
        ordering = ['-pk']

    def __unicode__(self):
        return '%s - %s' % (unicode(self.patient), unicode(self.doctor))

    objects = TicketManager()


admin.site.register(Ticket)

medis/apps/tickets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import admin

from django.db import models


class Speciality(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование специальности')

    class Meta:
        verbose_name = 'Специальность'
        verbose_name_plural = 'Специальности'
        ordering = ['-pk']

    def __unicode__(self):
        return self.name


admin.site.register(Speciality)


class Doctor(models.Model):
    name = models.CharField(max_length=255, verbose_name='ФИО врача')
    specialty = models.ForeignKey(Speciality)

    class Meta:
        verbose_name = 'Врач'
        verbose_name_plural = 'Врачи'
        ordering = ['name', '-pk']

    def __unicode__(self):
        return self.name

admin.site.register(Doctor)


class Patient(models.Model):
    name = models.CharField(max_length=255, verbose_name='ФИО пациента')

    class Meta:
        verbose_name = 'Пациент'
        verbose_name_plural = 'Пациенты'
        ordering = ['name', '-pk']

    def __unicode__(self):
        return self.name

admin.site.register(Patient)


class TicketManager(models.Manager):
    def count_by_speciality(self, month, year):
        answer = {}
        for specialty in Speciality.objects.all():
            tickets = Ticket.objects.filter(doctor__in=specialty.doctor_set.all(), datetime__month=month,
                                                      datetime__year=year)
            patients = tickets.exclude(patient__isnull=True)
            answer[specialty.name] = {
                'tickets': tickets.count(),
                'patients': patients.count()
            }
        return answer

    def count_by_doctor(self, specialty, month, year):
        answer = {}
        for doctor in Doctor.objects.filter(specialty=specialty):
            tickets = Ticket.objects.filter(doctor=doctor, datetime__month=month, datetime__year=year)
            patients = tickets.exclude(patient__isnull=True)
            answer[doctor.name] = {
                'tickets': tickets.count(),
                'patients': patients.count()
            }
        return answer


class Ticket(models.Model):
    doctor = models.ForeignKey(Doctor)
    datetime = models.DateTimeField()
    patient = models.ForeignKey(Patient, null=True, blank=True)

    class Meta:
        verbose_name = 'Талон'
        verbose_name_plural = 'Талоны'
        ordering = ['-pk']

    def __unicode__(self):
        return '%s - %s' % (unicode(self.patient), unicode(self.doctor))

    objects = TicketManager()


admin.site.register(Ticket)

medis/apps/stats/forms.py
import calendar
from datetime import datetime

from django import forms


class FilterForm(forms.Form):
    MONTH_CHOICES = tuple((idx, name) for idx, name in enumerate(calendar.month_name[1:], start=1))
    YEAR_CHOICES = tuple((n, str(n)) for n in range(2010, datetime.now().year + 1))
    month = forms.ChoiceField(choices=MONTH_CHOICES, initial=datetime.now().month)
    year = forms.ChoiceField(choices=YEAR_CHOICES, initial=datetime.now().year)

medis/apps/stats/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from datetime import datetime

from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
from django.views.generic import TemplateView

from medis.apps.stats.forms import FilterForm
from medis.apps.stats.models import Speciality, Ticket


class MonthStatsView(TemplateView):
    template_name = 'stats/month.html'

    def get_form_errors(self, form):
        return dict([(k, [unicode(e) for e in v]) for k, v in form.errors.items()])

    def data_to_json(self, context_dict):
        return json.dumps(context_dict, cls=DjangoJSONEncoder)

    def get_context_data(self, **kwargs):
        context = super(MonthStatsView, self).get_context_data(**kwargs)
        current_date = datetime.now()
        data = Ticket.objects.get_monthly_stats(current_date.month, current_date.year)
        context['form'] = self.form
        context['current_date'] = current_date
        context['data'] = data
        return context

    def get_json_response(self):
        if self.form.is_valid():
            data = Ticket.objects.get_monthly_stats(self.form.data['month'], self.form.data['year'])
            return HttpResponse(self.data_to_json(data), content_type='application/json')
        json_content = self.data_to_json(self.get_form_errors(self.form))
        return HttpResponse(json_content, content_type='application/json', status=400)

    def get(self, request, *args, **kwargs):
        self.form = FilterForm(request.GET)
        if self.request.is_ajax():
            return self.get_json_response()
        context = self.get_context_data()
        return self.render_to_response(context)


class SpecialityStatsView(TemplateView):
    template_name = 'stats/speciality.html'

    def get(self, request, *args, **kwargs):
        speciality = Speciality.objects.get_or_none(pk=request.GET.get('speciality'))
        form = FilterForm(request.GET)
        if form.is_valid() and speciality:
            context = super(SpecialityStatsView, self).get_context_data(**kwargs)
            data = Ticket.objects.get_speciality_stats(speciality, request.GET['month'], request.GET['year'])
            context.update({
                'speciality_name': speciality.name,
                'data': data
            })
            return self.render_to_response(context)
        else:
            return HttpResponse('Bad Request', status=400)

medis/apps/tickets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from datetime import datetime

from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.views.generic import View, FormView

from medis.apps.tickets.forms import FilterForm
from medis.apps.tickets.models import Ticket


class AjaxTicketsList(View):
    def get_form_errors(self, form):
        return dict([(k, [unicode(e) for e in v]) for k, v in form.errors.items()])

    def data_to_json(self, context_dict):
        return json.dumps(context_dict, cls=DjangoJSONEncoder)

    def render_json_response(self, json_context='', status=200):
        return HttpResponse(json_context, content_type='application/json', status=status)

    def render_form_error_json_response(self, form, status=400):
        json_context = self.data_to_json(self.get_form_errors(form))
        return HttpResponse(json_context, content_type='application/json', status=status)

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = FilterForm(request.POST)
            if form.is_valid():
                data = {
                    'stats_data': Ticket.objects.count_by_speciality(form.data['month'], form.data['year'])
                }
                return self.render_json_response(self.data_to_json(data))
            else:
                return self.render_form_error_json_response(form)
        else:
            return self.render_json_response('', 404)


class MonthStatsView(FormView):
    form_class = FilterForm
    template_name = 'tickets/month_stats.html'

    def get_context_data(self, **kwargs):
        context = super(MonthStatsView, self).get_context_data(**kwargs)

        current_date = datetime.now()
        data = Ticket.objects.count_by_speciality(current_date.month, current_date.year)
        context.update({'stats_data': data})
        return context

medis/templates/stats/month.html
{% extends "base.html" %}

{% load static %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/pages/stats.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <form id="filter-form" class="form-inline" method="get" role="form" action>
            {% csrf_token %}
            <h2 class="form-signin-heading">Месечная статистика количества посещений</h2>
            {{ form.non_field_errors }}

            <div class="form-group">
                <select class="form-control" name="month" id="id_month">
                    {% for choice in form.month.field.choices %}
                        <option {% if choice.0 == form.month.field.initial %}selected{% endif %}
                                value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <select class="form-control" name="year" id="id_year">
                    {% for choice in form.year.field.choices %}
                        <option {% if choice.0 == form.year.field.initial %}selected{% endif %}
                                value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
        </form>
    </div>

    <div class="row">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Специальность</th>
                <th>Кол-во талонов</th>
                <th>Кол-во пациентов</th>
            </tr>
            </thead>
            {% for speciality in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'stats:month-speciality'%}?speciality={{ speciality.pk }}&month={{ current_date.month }}&year={{ current_date.year }}">
                        {{ speciality.name }}
                    </a></td>
                    <td>{{ speciality.tickets }}</td>
                    <td>{{ speciality.patients }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

medis/templates/stats/speciality.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <div class="row">
        <h2>{{ speciality_name }}</h2>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Врач</th>
                <th>Кол-во талонов</th>
                <th>Кол-во пациентов</th>
            </tr>
            </thead>
            {% for doctor in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ doctor.name }}</td>
                    <td>{{ doctor.tickets }}</td>
                    <td>{{ doctor.patients }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}